' This is a UML diagram that shows the main classes implemented
' in the model and their members (data components and procedures
' defined within the class.
'
' Note: You can produce the graphics from this code using the plantuml
'       program or on the web: https://www.plantuml.com/plantuml/uml
'
' plantuml -tsvg class.plantuml
'
@startuml

  ' ------------------------------
  ' the environment class structure
  ' ------------------------------

  CELL --|> LOCATION
  LOCATION : x


  CELL : food_availability
  CELL : risk_of_predation
  CELL : +init()

  WHOLE_ENVIRON --o CELL : array of \nCELLs (point)
  WHOLE_ENVIRON : point
  WHOLE_ENVIRON : +init()


  ' ------------------------------
  ' the organism class structure
  ' ------------------------------


  ' We have class GENE as the basic, and BIRD extends GENE
  '   (This is shown by an arrow that goes from derived towards the
  '    basic class)
  BIRD --|> GENE

  ' GENE class has hunger variable
  '      and init() procedure

  GENE : +hunger
  GENE : +init()

  ' BIRD class has weight variable
  '      and grow() procedure

  BIRD : +weight
  BIRD : +grow()

@enduml
